### ISSUE TITLE
Dúvida sobre sistema operacional

### ISSUE THREAD

**Issue by LucasAlvarenga-dev** [lizarb/lizarb#1]
A Liza roda no Windows?

Qual a recomendação da equipe para detectar se o sistema operacional é Windows, Linux ou Mac? Vocês recomendam algum gem?

**Comment by thiagopintodev** [comment]
Otima pergunta!

Segundo a [Wikipedia](https://en.wikipedia.org/wiki/Shell_(computing)), Shell eh o nome dado a programas que expoe o Sistema Operacional para o usuario e para outros programas.

Vamos criar um Controller chamado Shell, e vamos implementar pelo menos esses 3 metodos de classe. Quem consegue criar essa PR?

```
class DevSystem
  class Shell < Liza::Controller
    def self.windows?
    end

    def self.linux?
    end

    def self.mac?
    end
  end
end
```

**Comment by ch1ago** [comment]
### Otima pergunta!

Segundo a [Wikipedia](https://en.wikipedia.org/wiki/Shell_(computing)), Shell eh o nome dado a programas que expoe o Sistema Operacional para o usuario e para outros programas.

Vamos criar um Controller chamado Shell, e vamos implementar pelo menos esses 3 metodos de classe.

**Quem consegue montar esse codigo?**

---

Algumas sugestoes:

1. Lembre-se de escrever um arquivo de teste.
2. A gente pode deixar para testar essas funcoes para um proximo issue.
3. Localizacao e template para usar no arquivo

```
# lib/dev_system/dev/controllers/shell.rb
# lib/dev_system/dev/controllers/shell_test.rb

class DevSystem
  class Shell < Liza::Controller
    def self.windows?
    end

    def self.linux?
    end

    def self.mac?
    end
  end
end
```
