### ISSUE TITLE
Console interativo PRY

### ISSUE THREAD

**Issue by cassioh** [lizarb/lizarb#3]
Vi que a Liza funciona com IRB, mas eu estava aprendendo sobre PRY num vídeo na internet. Eu posso adicionar PRY também?

**Comment by ch1ago** [comment]
### Muito boa pergunta.

Para abrir o console IRB na Liza, voce precisa rodar o comando abaixo.

```
liza dev
```


Eu acho que a melhor experiencia para o desenvolvedor seria a de poder escolher pelo IRB ou pelo PRY:

Gostaria de dar suporte aos seguintes comandos, onde se voce nao espeficicar, ele usa o IRB.

```
liza dev
liza dev irb
liza dev pry
```

O codigo atual do console IRB pode ser encontrado aqui:

https://github.com/rubyonrails-brasil/lizarb/blob/972d5ad962/lib/dev_system/dev/controllers/command/dev_command.rb#L7-L15

**Quem consegue montar esse codigo?**

**Comment by dnovais** [comment]
@thiagopintodev veja se faz sentido o [PR](https://github.com/rubyonrails-brasil/lizarb/pull/4).
