### ISSUE TITLE
Improviment: "Your Ruby version is 3.2.1, but your Gemfile specified 3.2.0"

### ISSUE THREAD

**Issue by juneira** [lizarb/lizarb#74]
### Problema

Quando usamos `liza new nome_do_projeto` ele cria um projeto setando a versão `3.2.0`, porém estou usando a versão `3.2.1`.

### Sugestão

Criar o arquivo `.ruby-version` usando a versão do Ruby que está rodando o script.

### Como está hoje

 `lib/dev_system/dev/controllers/generators/app_generator.rb`
```ruby
FileUtils.cp_r "#{Lizarb::APP_DIR}/.ruby-version", "#{to}/.ruby-version", verbose: true
```

`.ruby-version`
```
3.2.0
```

### Alteração

 `lib/dev_system/dev/controllers/generators/app_generator.rb`
```ruby
File.write('ruby_version.txt', RUBY_VERSION)
```

**Comment by ch1ago** [comment]
@juneira me desculpe por nao ter visto esse issue mais cedo.
Ele ja foi resolvido em https://github.com/rubyonrails-brasil/lizarb/commit/afac063e358b9f1afc5a4888a31ab6f3707bfdaa
