### ISSUE TITLE
lizarb generate command raises instead of showing usage information

### ISSUE THREAD

**Issue by abinoam** [lizarb/lizarb#76]
`lizarb` and  `lizarb generate` both show usage information
`lizarb generate command` raises an error instead

bug or feature?

**Comment by ch1ago** [comment]
Hi Abinoam. Thank you for opening this ticket.

As we spoke in the chat. Some of these errors were just rough edges from early in the development process.

This one forwards the call to NotFoundGenerator, and has already been fixed.

https://github.com/lizarb/lizarb/blob/87df3f3796b772b0e4547e336b2ebbf2d8abcc6e/lib/dev_system/sub/generator/generator_panel.rb#L72
